"""baseline schema

Revision ID: 1fde4747e043
Revises: 
Create Date: 2026-06-07 23:51:14.163972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fde4747e043'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('this_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('this_hash')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('fips', sa.String(length=10), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('methodology_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semver', sa.String(length=20), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semver')
    )
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('branch', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bioguide_id', sa.String(length=20), nullable=True),
    sa.Column('fec_id', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bioguide_id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbrev', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('native_identifier', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=60), nullable=True),
    sa.Column('domain_confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('implemented', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_native_identifier'), 'actions', ['native_identifier'], unique=False)
    op.create_index(op.f('ix_actions_type'), 'actions', ['type'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=60), nullable=False),
    sa.Column('direction_good', sa.String(length=10), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('native_series_id', sa.String(length=80), nullable=False),
    sa.Column('domain', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('office_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_landing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('native_identifier', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_path', sa.String(length=600), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_landing_content_hash'), 'raw_landing', ['content_hash'], unique=False)
    op.create_table('bills',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('congress', sa.Integer(), nullable=True),
    sa.Column('bill_number', sa.String(length=40), nullable=True),
    sa.Column('sponsor_official_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('became_law_action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['became_law_action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['sponsor_official_id'], ['officials.id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('executive_orders',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('eo_number', sa.String(length=20), nullable=True),
    sa.Column('signing_official_id', sa.Integer(), nullable=True),
    sa.Column('fr_doc_number', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['signing_official_id'], ['officials.id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_executive_orders_eo_number'), 'executive_orders', ['eo_number'], unique=False)
    op.create_table('laws',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('public_law_number', sa.String(length=40), nullable=True),
    sa.Column('statutes_at_large_cite', sa.String(length=80), nullable=True),
    sa.Column('enacted_date', sa.Date(), nullable=True),
    sa.Column('signed_by_official_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['signed_by_official_id'], ['officials.id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_laws_public_law_number'), 'laws', ['public_law_number'], unique=False)
    op.create_table('objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('objective_level', sa.String(length=20), nullable=False),
    sa.Column('registered_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('verified_against', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['verified_against'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_id', 'jurisdiction_id', 'period', name='uq_obs_series_period')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('vote_date', sa.Date(), nullable=True),
    sa.Column('yea', sa.Integer(), nullable=False),
    sa.Column('nay', sa.Integer(), nullable=False),
    sa.Column('present', sa.Integer(), nullable=False),
    sa.Column('not_voting', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('lag_window_months', sa.Integer(), nullable=True),
    sa.Column('sign_goal', sa.Integer(), nullable=True),
    sa.Column('alignment', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('evaluation_mode', sa.String(length=12), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('realized_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('directly_attributable', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('non_scoreable_reason', sa.String(length=200), nullable=True),
    sa.Column('prereg_hash', sa.String(length=64), nullable=True),
    sa.Column('prereg_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objective_metric_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('alignment_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribution_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eu_id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('authority', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('pivotality', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('attribution', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('attr_ci_low', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('attr_ci_high', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_residual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['eu_id'], ['evaluation_units.id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eu_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('ci_low', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('ci_high', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['eu_id'], ['evaluation_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcome_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eu_id', sa.Integer(), nullable=False),
    sa.Column('observed', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('baseline_pooled', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('delta', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('z', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('model_dependence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('ci_low', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('ci_high', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['eu_id'], ['evaluation_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eu_id', sa.Integer(), nullable=False),
    sa.Column('methodology_version_id', sa.Integer(), nullable=False),
    sa.Column('data_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('code_git_sha', sa.String(length=40), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reproducible_hash', sa.String(length=64), nullable=True),
    sa.Column('input_source_urls', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eu_id'], ['evaluation_units.id'], ),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_runs_reproducible_hash'), 'score_runs', ['reproducible_hash'], unique=False)
    op.create_table('confidence_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_run_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(length=40), nullable=False),
    sa.Column('ci_low', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('ci_high', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['score_run_id'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eu_id', sa.Integer(), nullable=False),
    sa.Column('filer', sa.String(length=120), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution_run_id', sa.Integer(), nullable=True),
    sa.Column('public_diff', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eu_id'], ['evaluation_units.id'], ),
    sa.ForeignKeyConstraint(['resolution_run_id'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eu_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_run_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('composite', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gated', sa.Boolean(), nullable=False),
    sa.Column('coverage', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['score_run_id'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_run_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('ci_low', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ci_high', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_value_laden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['score_run_id'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_components')
    op.drop_table('eu_scores')
    op.drop_table('disputes')
    op.drop_table('confidence_intervals')
    op.drop_index(op.f('ix_score_runs_reproducible_hash'), table_name='score_runs')
    op.drop_table('score_runs')
    op.drop_table('outcome_results')
    op.drop_table('baselines')
    op.drop_table('attribution_weights')
    op.drop_table('vote_positions')
    op.drop_table('objective_metric_map')
    op.drop_table('evaluation_units')
    op.drop_table('votes')
    op.drop_table('observations')
    op.drop_table('objectives')
    op.drop_index(op.f('ix_laws_public_law_number'), table_name='laws')
    op.drop_table('laws')
    op.drop_index(op.f('ix_executive_orders_eo_number'), table_name='executive_orders')
    op.drop_table('executive_orders')
    op.drop_table('bills')
    op.drop_index(op.f('ix_raw_landing_content_hash'), table_name='raw_landing')
    op.drop_table('raw_landing')
    op.drop_table('office_terms')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_actions_type'), table_name='actions')
    op.drop_index(op.f('ix_actions_native_identifier'), table_name='actions')
    op.drop_table('actions')
    op.drop_table('parties')
    op.drop_table('officials')
    op.drop_table('offices')
    op.drop_table('methodology_versions')
    op.drop_table('jurisdictions')
    op.drop_table('data_sources')
    op.drop_table('audit_records')
    # ### end Alembic commands ###
