"""add hot-path indexes

Revision ID: 8c5a96609f70
Revises: 1fde4747e043
Create Date: 2026-06-07 23:53:12.521366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5a96609f70'
down_revision: Union[str, Sequence[str], None] = '1fde4747e043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attribution_weights_eu_id'), 'attribution_weights', ['eu_id'], unique=False)
    op.create_index(op.f('ix_attribution_weights_official_id'), 'attribution_weights', ['official_id'], unique=False)
    op.create_index(op.f('ix_evaluation_units_action_id'), 'evaluation_units', ['action_id'], unique=False)
    op.create_index(op.f('ix_evaluation_units_status'), 'evaluation_units', ['status'], unique=False)
    op.create_index(op.f('ix_outcome_results_eu_id'), 'outcome_results', ['eu_id'], unique=False)
    op.create_index(op.f('ix_score_components_score_run_id'), 'score_components', ['score_run_id'], unique=False)
    op.create_index(op.f('ix_score_runs_eu_id'), 'score_runs', ['eu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_runs_eu_id'), table_name='score_runs')
    op.drop_index(op.f('ix_score_components_score_run_id'), table_name='score_components')
    op.drop_index(op.f('ix_outcome_results_eu_id'), table_name='outcome_results')
    op.drop_index(op.f('ix_evaluation_units_status'), table_name='evaluation_units')
    op.drop_index(op.f('ix_evaluation_units_action_id'), table_name='evaluation_units')
    op.drop_index(op.f('ix_attribution_weights_official_id'), table_name='attribution_weights')
    op.drop_index(op.f('ix_attribution_weights_eu_id'), table_name='attribution_weights')
    # ### end Alembic commands ###
